# Generated by Django 3.2.8 on 2021-10-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('projects', '0002_remove_project_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='configuration',
            field=models.ManyToManyField(to='configurations.Configuration'),
        ),
    ]
